services:
  svitlo-monitor:
    build: .
    container_name: svitlo-monitor
    restart: unless-stopped
    env_file: .env
  fake-svitlo-api:
    build: ./fake_api
    container_name: fake-svitlo-api
    restart: unless-stopped
    ports:
      - "8000:8000"