version: "3.9"

services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard:latest
    container_name: svitlo-wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - ./wg:/config
      - /lib/modules:/lib/modules:ro
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    # Expose ports here if you need to access UI from outside, 
    # but other containers will use 'network_mode: service' so they don't need ports here.